org: darylsinon
app: api
service: khelraja
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10
  # stage: ${opt:stage}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    resourceRoutes: true
  # stage: ${opt:stage, self:provider.stage}
  # webpack:
  #   webpackConfig: ../../webpack.config.js
  #   includeModules: true
# functions:
#   hello:
#     handler: handler.hello
#     events:
#       - httpApi:
#           path: /
#           method: get
