org: darylsinon
app: api
service: khelraja
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
